// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTCCyC_ZJct2mNjAY5NhPjtn-U7dJWEXo',
    appId: '1:287611709005:web:d7f43ae934854803605e04',
    messagingSenderId: '287611709005',
    projectId: 'flutter-training-f4246',
    authDomain: 'flutter-training-f4246.firebaseapp.com',
    storageBucket: 'flutter-training-f4246.appspot.com',
    measurementId: 'G-9WL13YG123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0SZ0gHMlQMiNxZ-Dk6yy_R-7Z_LBVt4',
    appId: '1:287611709005:android:ea7d0d1a68ecc451605e04',
    messagingSenderId: '287611709005',
    projectId: 'flutter-training-f4246',
    storageBucket: 'flutter-training-f4246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFM_nX8VWqaYUwEiiOFC08zKFB8hh_8gs',
    appId: '1:287611709005:ios:232e66cb12a14fc7605e04',
    messagingSenderId: '287611709005',
    projectId: 'flutter-training-f4246',
    storageBucket: 'flutter-training-f4246.appspot.com',
    iosBundleId: 'com.littleboy.firebaseTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFM_nX8VWqaYUwEiiOFC08zKFB8hh_8gs',
    appId: '1:287611709005:ios:d7027836610a2a89605e04',
    messagingSenderId: '287611709005',
    projectId: 'flutter-training-f4246',
    storageBucket: 'flutter-training-f4246.appspot.com',
    iosBundleId: 'com.littleboy.firebaseTraining.RunnerTests',
  );
}
